export default [
  {
    Id: 1,
    genre: 1,
    seller: 'Alvaro Sanquiz',
    title: 'Brand new The Dark Side of the Moon vinyl',
    artist: 'Pink Floyd',
    price: 34,
    picture: '/tdsofm.jpg',
  },
  {
    Id: 2,
    genre: 1,
    seller: 'Jesus Salazar',
    title: 'Weezer (Blue Album) on sale',
    artist: 'Weezer',
    price: 34,
    picture: '/bluealbum.jpg',
  },
  {
    Id: 3,
    genre: 1,
    seller: 'Oliver Contreras',
    title: 'Spiderland',
    artist: 'Slint',
    price: 34,
    picture: '/spiderland.jpg',
  },
  {
    Id: 4,
    genre: 2,
    seller: 'Diego Alfonso',
    title: 'MM... FOOD',
    artist: 'MF DOOM',
    price: 34,
    picture: '/mmfood.jpg',
  },
  {
    Id: 5,
    genre: 2,
    seller: 'Juan Morillo',
    title: 'My Beautiful Dark Twisted Fantasy',
    artist: 'Kanye West',
    price: 34,
    picture: '/mbdtf.jpg',
  },
  {
    Id: 6,
    genre: 2,
    seller: 'Luis Sindelay',
    title: 'Illmatic',
    artist: 'Nas',
    price: 34,
    picture: '/illmatic.jpg',
  },
  {
    Id: 7,
    genre: 3,
    seller: 'Fabian Garcia',
    title: 'Ride The Lightning',
    artist: 'Metallica',
    price: 34,
    picture: '/rtl.jpg',
  },
  {
    Id: 8,
    genre: 3,
    seller: 'Angel Simental',
    title: 'Around The Fur',
    artist: 'Deftones',
    price: 34,
    picture: '/atf.jpg',
  },
  {
    Id: 9,
    genre: 3,
    seller: 'Anthony Fanthano',
    title: 'Symbolic',
    artist: 'Death',
    price: 34,
    picture: '/symbolic.jpg',
  },
];
